spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:application.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/zani
    username: sa
    password: 1234

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          default_batch_fetch_size: 100
          show_sql: true
          format_sql: true
      database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080
