spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:application.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zani?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ekdmsl1216

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          default_batch_fetch_size: 100
          show_sql: true
          format_sql: true
      database-platform: org.hibernate.dialect.MYSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080
